Collections:
  - Name: Autoformer
    Metadata:
      Training Data:
        - ImageNet-1k
    Paper:
      URL: https://arxiv.org/abs/2107.00651
      Title: Searching Transformers for Visual Recognition
    README: configs/nas/mmcls/spos/README.md
    Code:
      URL: https://github.com/open-mmlab/mmrazor/blob/dev-1.x/mmrazor/models/algorithms/autoformer.py
      Version: v0.1.0
    Converted From:
      Code: https://github.com/microsoft/Cream/tree/main/AutoFormer
Models:
  - Name: autoformer_supernet_32xb256_in1k
    In Collection: Autoformer
    Metadata:
      FLOPs: 330 MB
      Subnet: https://download.openmmlab.com/mmrazor/v1/spos/spos_shufflenetv2_subnet_8xb128_in1k_flops_0.33M_acc_73.87_20220715-aa94d5ef_subnet_cfg_v1.yaml
    Results:
      - Task: Image Classification
        Dataset: ImageNet-1k
        Metrics:
          Top 1 Accuracy: 82.51
          Top 5 Accuracy: 96.05
    Config: configs/nas/mmcls/autoformer/autoformer_supernet_32xb256_in1k.py
    Weights: https://download.openmmlab.com/mmrazor/v1/spos/spos_shufflenetv2_subnet_8xb128_in1k_flops_0.33M_acc_73.87_20211222-1f0a0b4d_v1.pth
